name: Build
'on':
  - push
jobs:
  ubuntu-20-04-build-gcc:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt install -y cmake gcc g++ libglpk-dev coinor-cbc coinor-libcbc-dev
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
  ubuntu-22-04-build-gcc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt install -y cmake gcc g++ libglpk-dev coinor-cbc coinor-libcbc-dev
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
  ubuntu-24-04-build-gcc:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt install -y cmake gcc g++ libglpk-dev coinor-cbc coinor-libcbc-dev
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
  ubuntu-latest-build-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt install -y cmake gcc g++ libglpk-dev coinor-cbc coinor-libcbc-dev
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
  ubuntu-20-04-build-clang:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt install -y cmake clang libglpk-dev coinor-cbc coinor-libcbc-dev
      - name: cmake
        run: mkdir build && cd build && cmake ..
        shell: bash
        env:
          CC: clang
          CXX: clang++
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
  ubuntu-22-04-build-clang:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt install -y cmake clang libglpk-dev coinor-cbc coinor-libcbc-dev
      - name: cmake
        run: mkdir build && cd build && cmake ..
        shell: bash
        env:
          CC: clang
          CXX: clang++
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
  ubuntu-24-04-build-clang:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt install -y cmake clang libglpk-dev coinor-cbc coinor-libcbc-dev
      - name: cmake
        run: mkdir build && cd build && cmake ..
        shell: bash
        env:
          CC: clang
          CXX: clang++
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
  ubuntu-latest-build-clang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt install -y cmake clang libglpk-dev coinor-cbc coinor-libcbc-dev
      - name: cmake
        run: mkdir build && cd build && cmake ..
        shell: bash
        env:
          CC: clang
          CXX: clang++
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
  macos-14-build:
    runs-on: macos-14
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: install dependencies
        run: brew install --force --overwrite cmake && brew install --force --overwrite glpk && brew tap coin-or-tools/coinor && brew install --force --overwrite coin-or-tools/coinor/cbc
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
  macos-13-build:
    runs-on: macos-13
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: install dependencies
        run: brew install --force --overwrite cmake && brew install --force --overwrite glpk && brew tap coin-or-tools/coinor && brew install --force --overwrite coin-or-tools/coinor/cbc
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
  macos-12-build:
    runs-on: macos-12
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: install dependencies
        run: brew install --force --overwrite cmake && brew install --force --overwrite glpk 
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
  macos-11-build:
    runs-on: macos-11
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: install dependencies
        run: brew install --force --overwrite cmake && brew install --force --overwrite glpk 
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
